### ISSUE TITLE
Problem with --save-video

### ISSUE THREAD

**Issue by fabianmueller1997** [bbolli/tumblr-utils#97]
Hey,

first of all, I'd like to say thank you for this great tool. It's been very handy for me.
There is, however, a problem with the --save-video option: When I try to download the contents of a 'video-heavy' (NSFW) blog, I end up with lots of incomplete videos. Most of the downloaded files have a size of roughly 3 MiB which seems quite strange. As a result, the incomplete videos only play for a few seconds of their original duration. 
Maybe there is some sort of limit that prevents larger videos from being downloaded? Perhaps I should add that my internet connection is quite slow.
Another thing I noticed was that - during the process of downloading videos - the script produces a lot of errors.
I am using this version of the script with Python 3: https://github.com/bbolli/tumblr-utils/pull/96 I also installed the latest version of youtube-dl with 'pip install -U youtube-dl' The Linux distribution I am using is Manjaro i3 (17.0.6). 
I hope there is some sort of solution to this problem.

**Comment by vxbinaca** [comment]
You should use pip3 for youtube-dl, and update your tumblr-utils I believe I pushed out a fix for the failing rips around the time you made this issue. I set the failure threshold for 3000 retries which is insane but should stabilize it well.

**Comment by Lyte3000** [comment]
I didn't use pip3 to install youtube-dl, but I used pip. It still doesn't download full videos

**Comment by vxbinaca** [comment]
Upgrade to the latest version of `tumblr-utils` and try again, It should have an insane timeout for videos. If that doesn't fix it try to obtain better internet.
